    <header>
        <div style='display:flex;flex-direction:row;'>
            <img src='logo.png' style='aspect-ratio:1/1;height:80px;'>
            <h1 style='align-self:center; margin-left:20px;'>Атмосфера знаний</h1>
        </div>
        <nav>
            <ul>
                <li><a href="index.php">Главная</a></li>
                <li><a href="catalog.php">Каталог</a></li>
                <li><a href="Lcab.php">Личный кабинет</a></li>
                <li><a href="#"></a></li>
                <li><a href="registration.php">Вход/Регистрация</a></li>
            </ul>
        </nav>
    </header>